version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: TravelJournal
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  backend:
    build: ./backend
    container_name: travel-backend
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=TravelJournal;user=root;password=password
    networks:
      - travelnet

  frontend:
    build: ./frontend
    container_name: travel-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - travelnet

volumes:
  dbdata:

networks:
  travelnet:
